# Generated by Django 5.1.3 on 2024-12-09 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField()),
                ('forecast_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(db_column='product_sku', on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='planning.product')),
            ],
        ),
    ]
