# Generated by Django 5.1.3 on 2024-12-09 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0006_forecast'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='version',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
