# Generated by Django 5.1.3 on 2024-12-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0007_forecast_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
